CREATE TABLE gtfs_schedule (
    trip_id BIGINT,
    arrival_time TEXT,
    departure_time TEXT,
    stop_id TEXT,
    stop_sequence INTEGER,
    route_id INTEGER,
    service_id TEXT,
    trip_headsign TEXT,
    direction_id INTEGER,
    shape_id INTEGER,
    wheelchair_accessible INTEGER,
    agency_id TEXT,
    route_short_name INTEGER,
    route_long_name TEXT,
    route_type INTEGER,
    stop_code INTEGER,
    stop_name TEXT,
    stop_lat DOUBLE PRECISION,
    stop_lon DOUBLE PRECISION,
    location_type INTEGER,
    wheelchair_boarding INTEGER,
    hour INTEGER,
    hour_mod INTEGER,
    monday INTEGER,
    tuesday INTEGER,
    wednesday INTEGER,
    thursday INTEGER,
    friday INTEGER,
    saturday INTEGER,
    sunday INTEGER
);
